const CATEGORIES = [
  {id:'football', name:'Football', emoji:'⚽'},
  {id:'geography', name:'Geography', emoji:'🌍'},
  {id:'history', name:'History', emoji:'🏛️'},
  {id:'animals', name:'Animal round', emoji:'🐾'},
  {id:'music', name:'Music round', emoji:'🎧'},
  {id:'logos', name:'Logo round', emoji:'🔤'},
  {id:'landmarks', name:'Landmarks', emoji:'🗽'},
  {id:'random', name:'Random', emoji:'🎲'},
];

const QUESTION_BANK = {
  football: [
    {q:"How many players are on each football team on the pitch?", o:["11","10","9","12"], c:0, d:'easy'},
    {q:"What shape is a standard football pitch?", o:["Rectangle","Circle","Square","Triangle"], c:0, d:'easy'},
    {q:"Which country won the 2018 FIFA World Cup?", o:["France","Croatia","Brazil","Germany"], c:0, d:'medium'},
    {q:"Which club is nicknamed 'The Red Devils'?", o:["Manchester United","Liverpool","Arsenal","Chelsea"], c:0, d:'medium'},
    {q:"Who is the all-time top scorer in Champions League history?", o:["Cristiano Ronaldo","Lionel Messi","Robert Lewandowski","Karim Benzema"], c:0, d:'hard'},
    {q:"Which country has won the most FIFA World Cups?", o:["Brazil","Germany","Italy","Argentina"], c:0, d:'hard'},
    {q:"What do you call it when a player scores three goals in one match?", o:["Hat-trick","Treble","Triple","Grand slam"], c:0, d:'easy'},
    {q:"Which colour card sends a player off the pitch?", o:["Red","Yellow","Blue","Green"], c:0, d:'easy'},
    {q:"How long is a standard football match, excluding stoppage time?", o:["90 minutes","80 minutes","100 minutes","60 minutes"], c:0, d:'medium'},
    {q:"Which country is credited with inventing modern football?", o:["England","Brazil","Italy","Spain"], c:0, d:'medium'},
    {q:"Which player has won the most Ballon d'Or awards?", o:["Lionel Messi","Cristiano Ronaldo","Michel Platini","Johan Cruyff"], c:0, d:'hard'},
    {q:"In which year was the first FIFA World Cup held?", o:["1930","1926","1934","1922"], c:0, d:'hard'},
  ],
  geography: [
    {q:"What is the largest continent by area?", o:["Asia","Africa","Europe","North America"], c:0, d:'easy'},
    {q:"Which ocean is the largest?", o:["Pacific","Atlantic","Indian","Arctic"], c:0, d:'easy'},
    {q:"Which country has the most natural lakes?", o:["Canada","Russia","USA","Finland"], c:0, d:'medium'},
    {q:"What is the longest river in the world?", o:["Nile","Amazon","Yangtze","Mississippi"], c:0, d:'medium'},
    {q:"Which African country was formerly known as Abyssinia?", o:["Ethiopia","Sudan","Kenya","Somalia"], c:0, d:'hard'},
    {q:"What is the driest desert in the world?", o:["Atacama","Sahara","Gobi","Mojave"], c:0, d:'hard'},
    {q:"Which is the smallest country in the world?", o:["Vatican City","Monaco","San Marino","Malta"], c:0, d:'easy'},
    {q:"On which continent is the Sahara Desert?", o:["Africa","Asia","South America","Australia"], c:0, d:'easy'},
    {q:"Which country has the most time zones?", o:["France","Russia","USA","China"], c:0, d:'medium'},
    {q:"What is the capital of Australia?", o:["Canberra","Sydney","Melbourne","Perth"], c:0, d:'medium'},
    {q:"Which strait separates Europe from Africa at its narrowest point?", o:["Strait of Gibraltar","Bosphorus Strait","Strait of Hormuz","Bering Strait"], c:0, d:'hard'},
    {q:"Which country has the longest coastline in the world?", o:["Canada","Russia","Indonesia","Australia"], c:0, d:'hard'},
  ],
  history: [
    {q:"In which year did World War II end?", o:["1945","1944","1939","1950"], c:0, d:'easy'},
    {q:"Who was the first President of the United States?", o:["George Washington","Thomas Jefferson","Abraham Lincoln","John Adams"], c:0, d:'easy'},
    {q:"Which empire built the Colosseum?", o:["Roman Empire","Greek Empire","Ottoman Empire","Persian Empire"], c:0, d:'medium'},
    {q:"The Great Wall of China was mainly built to defend against?", o:["Northern invaders","Pirates","Rebel armies","Trade rivals"], c:0, d:'medium'},
    {q:"In which year did the Berlin Wall fall?", o:["1989","1991","1985","1993"], c:0, d:'hard'},
    {q:"Who was the last Tsar of Russia?", o:["Nicholas II","Alexander III","Peter the Great","Ivan the Terrible"], c:0, d:'hard'},
    {q:"Which ship famously sank in 1912 after hitting an iceberg?", o:["Titanic","Britannic","Lusitania","Olympic"], c:0, d:'easy'},
    {q:"Who painted the Mona Lisa?", o:["Leonardo da Vinci","Michelangelo","Raphael","Donatello"], c:0, d:'easy'},
    {q:"The Renaissance began in which country?", o:["Italy","France","Germany","Spain"], c:0, d:'medium'},
    {q:"Who was the British Prime Minister for most of World War II?", o:["Winston Churchill","Neville Chamberlain","Clement Attlee","Anthony Eden"], c:0, d:'medium'},
    {q:"In which year did the French Revolution begin?", o:["1789","1776","1804","1815"], c:0, d:'hard'},
    {q:"Which empire was ruled by Genghis Khan?", o:["Mongol Empire","Ottoman Empire","Persian Empire","Roman Empire"], c:0, d:'hard'},
  ],
  animals: [
    {q:"What is the largest land animal?", o:["African elephant","Giraffe","Rhino","Hippo"], c:0, d:'easy'},
    {q:"How many legs does a spider have?", o:["8","6","10","4"], c:0, d:'easy'},
    {q:"What is a baby kangaroo called?", o:["Joey","Cub","Kid","Pup"], c:0, d:'medium'},
    {q:"Which bird is known for mimicking human speech?", o:["Parrot","Crow","Eagle","Owl"], c:0, d:'medium'},
    {q:"What is the fastest land animal?", o:["Cheetah","Lion","Pronghorn","Gazelle"], c:0, d:'hard'},
    {q:"Which mammal is known to lay eggs?", o:["Platypus","Bat","Dolphin","Otter"], c:0, d:'hard'},
    {q:"Which animal is known as the 'King of the Jungle'?", o:["Lion","Tiger","Elephant","Gorilla"], c:0, d:'easy'},
    {q:"How many hearts does an octopus have?", o:["3","1","2","4"], c:0, d:'easy'},
    {q:"Which animal can change the colour of its skin to blend in?", o:["Chameleon","Frog","Lizard","Gecko"], c:0, d:'medium'},
    {q:"What is a group of lions called?", o:["Pride","Pack","Herd","Flock"], c:0, d:'medium'},
    {q:"Which is the only mammal capable of true flight?", o:["Bat","Flying squirrel","Sugar glider","Colugo"], c:0, d:'hard'},
    {q:"How many hearts does an earthworm have?", o:["5","1","2","4"], c:0, d:'hard'},
  ],
  music: [
    {q:"How many strings does a standard guitar have?", o:["6","4","8","5"], c:0, d:'easy'},
    {q:"Which instrument has black and white keys?", o:["Piano","Violin","Trumpet","Drum"], c:0, d:'easy'},
    {q:"Which decade is disco music most associated with?", o:["1970s","1980s","1960s","1990s"], c:0, d:'medium'},
    {q:"What does 'tempo' refer to in music?", o:["The speed of the music","The volume","The pitch","The key"], c:0, d:'medium'},
    {q:"Which orchestral section includes the cello?", o:["Strings","Brass","Woodwind","Percussion"], c:0, d:'hard'},
    {q:"What's the term for singing with no instruments at all?", o:["A cappella","Falsetto","Vibrato","Staccato"], c:0, d:'hard'},
    {q:"How many keys are on a standard piano?", o:["88","76","100","64"], c:0, d:'easy'},
    {q:"Which family of instruments does the flute belong to?", o:["Woodwind","Brass","String","Percussion"], c:0, d:'easy'},
    {q:"What does 'forte' mean in music?", o:["Loud","Soft","Fast","Slow"], c:0, d:'medium'},
    {q:"Which decade is grunge music most associated with?", o:["1990s","1980s","1970s","2000s"], c:0, d:'medium'},
    {q:"What is the standard tuning pitch for the note A above middle C?", o:["440Hz","432Hz","450Hz","420Hz"], c:0, d:'hard'},
    {q:"Which term describes music played with no fixed, strict beat?", o:["Rubato","Staccato","Legato","Vibrato"], c:0, d:'hard'},
  ],
  logos: [
    {q:"Which brand's logo is a golden letter 'M'?", o:["McDonald's","Burger King","Wendy's","Subway"], c:0, d:'easy'},
    {q:"Which brand's logo is a bitten apple?", o:["Apple","Samsung","Google","Microsoft"], c:0, d:'easy'},
    {q:"Which sportswear brand uses a 'swoosh' tick logo?", o:["Nike","Adidas","Puma","Reebok"], c:0, d:'medium'},
    {q:"Which car brand's logo is four interlocked rings?", o:["Audi","BMW","Volkswagen","Mercedes"], c:0, d:'medium'},
    {q:"Which coffee brand's logo is a green mermaid?", o:["Starbucks","Costa Coffee","Tim Hortons","Peet's"], c:0, d:'hard'},
    {q:"Which airline's logo features a leaping kangaroo?", o:["Qantas","Emirates","Etihad","Singapore Airlines"], c:0, d:'hard'},
    {q:"Which brand's logo is a red bullseye target?", o:["Target","Walmart","Kmart","Costco"], c:0, d:'easy'},
    {q:"Which brand's logo is a small blue bird?", o:["Twitter","Facebook","LinkedIn","Pinterest"], c:0, d:'easy'},
    {q:"Which streaming service's logo is a red letter 'N'?", o:["Netflix","Hulu","Disney+","Prime Video"], c:0, d:'medium'},
    {q:"Which tech brand's logo is a multicoloured windowpane?", o:["Microsoft","Google","IBM","Intel"], c:0, d:'medium'},
    {q:"Which organisation's logo is a black and white panda?", o:["WWF","Animal Planet","Greenpeace","National Geographic"], c:0, d:'hard'},
    {q:"Which brand's logo is a yellow and red shell shape?", o:["Shell","BP","Esso","Chevron"], c:0, d:'hard'},
  ],
  landmarks: [
    {q:"In which city is the Eiffel Tower located?", o:["Paris","London","Rome","Berlin"], c:0, d:'easy'},
    {q:"Which landmark is found in Agra, India?", o:["Taj Mahal","Red Fort","Golden Temple","Gateway of India"], c:0, d:'easy'},
    {q:"The Statue of Liberty was a gift from which country?", o:["France","UK","Spain","Italy"], c:0, d:'medium'},
    {q:"In which country would you find Machu Picchu?", o:["Peru","Mexico","Chile","Ecuador"], c:0, d:'medium'},
    {q:"Which ancient wonder stood in Alexandria?", o:["The Lighthouse","Hanging Gardens","Colossus","Great Pyramid"], c:0, d:'hard'},
    {q:"The Christ the Redeemer statue overlooks which city?", o:["Rio de Janeiro","Sao Paulo","Buenos Aires","Lima"], c:0, d:'hard'},
    {q:"In which city is the Colosseum located?", o:["Rome","Athens","Venice","Milan"], c:0, d:'easy'},
    {q:"Which landmark is a giant clock tower in London?", o:["Big Ben","London Eye","Tower Bridge","The Shard"], c:0, d:'easy'},
    {q:"Which country is home to the ancient city of Petra?", o:["Jordan","Egypt","Israel","Syria"], c:0, d:'medium'},
    {q:"The Great Barrier Reef lies off the coast of which country?", o:["Australia","Indonesia","Philippines","Thailand"], c:0, d:'medium'},
    {q:"In which city would you find the Hagia Sophia?", o:["Istanbul","Athens","Cairo","Jerusalem"], c:0, d:'hard'},
    {q:"Which mountain range separates Europe and Asia?", o:["Ural Mountains","Alps","Himalayas","Caucasus"], c:0, d:'hard'},
  ],
  random: [
    {q:"What color do you get by mixing blue and yellow?", o:["Green","Purple","Orange","Brown"], c:0, d:'easy'},
    {q:"How many days are in a leap year?", o:["366","365","364","367"], c:0, d:'easy'},
    {q:"What is the chemical symbol for gold?", o:["Au","Ag","Gd","Go"], c:0, d:'medium'},
    {q:"How many continents are there?", o:["7","5","6","8"], c:0, d:'medium'},
    {q:"What is the smallest prime number?", o:["2","1","0","3"], c:0, d:'hard'},
    {q:"What is the hardest natural substance on Earth?", o:["Diamond","Quartz","Titanium","Steel"], c:0, d:'hard'},
    {q:"How many sides does a hexagon have?", o:["6","5","7","8"], c:0, d:'easy'},
    {q:"What is the freezing point of water in Celsius?", o:["0","32","100","-10"], c:0, d:'easy'},
    {q:"Which planet is known as the Red Planet?", o:["Mars","Venus","Jupiter","Mercury"], c:0, d:'medium'},
    {q:"How many players are on a basketball team on court at once?", o:["5","6","7","4"], c:0, d:'medium'},
    {q:"What is the currency of Japan?", o:["Yen","Won","Yuan","Ringgit"], c:0, d:'hard'},
    {q:"Which gas do plants primarily absorb for photosynthesis?", o:["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"], c:0, d:'hard'},
  ],
};

const BOOST_DEFS = {
  freeze: {icon:'🧊', name:'Freeze', desc:"Stops a rival answering the next question", targeted:true},
  swap:   {icon:'🔄', name:'Swap', desc:"Swap your quiz score with a rival's", targeted:true},
  halve:  {icon:'✂️', name:'Halve', desc:"Cut a rival's quiz score in half", targeted:true},
  hide:   {icon:'🙈', name:'Blindfold', desc:"Hides a rival's answers for 3 questions", targeted:true},
  x2:     {icon:'⚡', name:'Double Up', desc:"Double your points for 3 questions", targeted:false},
};

const BOT_PROFILES = [
  {name:'Byte', emoji:'🤖', skill:0.12},
  {name:'Pixel', emoji:'👾', skill:0.0},
  {name:'Ziggy', emoji:'🦊', skill:-0.08},
  {name:'Nova', emoji:'🌙', skill:0.06},
];

module.exports = { CATEGORIES, QUESTION_BANK, BOOST_DEFS, BOT_PROFILES };
